name: Deploy to gh-pages

on:
  push:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "^18"

      - name: yarn install
        env:
          CI: true
        run: |
          yarn run clean
          yarn

      - name: Build
        env:
          ENV: "production"
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192
          yarn build

      - name: Simple deploy with git
        uses: rdarida/simple-github-pages-deploy-action@v1
        with: # optional
          git-base-folder: "dist"
          git-user: 'YewandeOjo'
          git-email: 'yewande_oluwafisayo@outlook.com'
